### ISSUE TITLE
Enhancement: External Links/Resources appearing in carousel

### ISSUE THREAD

**Issue by tremainebuchanan** [slashroots/slashroots-website-v2#71]
Currently, the carousel only accommodates and displays internal resources/pages/posts. As a user, I would like the ability to create a slide that points/links to an external resource.

**Comment by matjames007** [comment]
This can be accommodated by adding the full URL in the link field.

**Comment by matjames007** [comment]
I have verified this and I can definitely create a slide with a link to any content (external and internal).
